//type
const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
const SEARCH_USER_ERROR = "SEARCH_USER_ERROR";
const SET_SELECTED_USER = "SET_SELECTED_USER";
const SET_USER_DETAIL = "SET_USER_DETAIL";
const SET_USER_REPOS = "SET_USER_REPOS";

export {
  SEARCH_USER_REQUEST,
  SEARCH_USER_SUCCESS,
  SEARCH_USER_ERROR,
  SET_SELECTED_USER,
  SET_USER_DETAIL,
  SET_USER_REPOS,
};
